package PGL;

import org.springframework.data.repository.CrudRepository;
import PGL.User;

/**
 * Represents a user repository and is auto generated by spring-boot
 */
public interface UserRepository extends CrudRepository<User, Long> {

 User findByEmail(String email);

 User[] findByNameStartingWith (String name);

}